services:
  - type: web
    name: gargalib-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js

  - type: web
    name: gargalib-frontend
    runtime: static
    rootDir: my-app
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html